<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net8.0;netstandard2.0</TargetFrameworks>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<WarningLevel>3</WarningLevel>
		<NoWarn>IDE0003,IDE0054,IDE0056,IDE0057,IDE0063,IDE0074,IDE0090,CA1068,CA1510,CA1512,CA1822,CA2208,CS8002,NU1701,1573,1591</NoWarn>
		<DocumentationFile>bin/$(Configuration)/$(TargetFramework)/VIEApps.Components.Utility.xml</DocumentationFile>
		<RootNamespace>net.vieapps.Components.Utility</RootNamespace>
		<AssemblyName>VIEApps.Components.Utility</AssemblyName>
		<AssemblyTitle>VIEApps NGX Utility</AssemblyTitle>
		<AssemblyVersion>10.10$(ReleaseVersion)</AssemblyVersion>
		<FileVersion>10.10$(ReleaseVersion)</FileVersion>
		<InformationalVersion>10.10.$([System.DateTime]::Now.Year).$([System.DateTime]::Now.Month).$([System.DateTime]::Now.Day)@$(TargetFramework)#sn:$(Sign)#$(ReleaseRevision)</InformationalVersion>
		<Version>10.10$(ReleaseVersion)$(ReleaseSuffix)</Version>
		<Product>VIEApps NGX</Product>
		<Title>VIEApps NGX Utility</Title>
		<Description>The general purpose component for developing apps with .NET</Description>
		<Copyright>© $([System.DateTime]::Now.Year) VIEApps.net</Copyright>
		<Authors>VIEApps.net</Authors>
		<Company>VIEApps.net</Company>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<SignAssembly>$(Sign)</SignAssembly>
		<AssemblyOriginatorKeyFile>../VIEApps.Components.snk</AssemblyOriginatorKeyFile>
		<DefineConstants>$(SignConstant)</DefineConstants>
		<GeneratePackageOnBuild>$(GeneratePackage)</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageId>VIEApps.Components.Utility$(PackageSuffix)</PackageId>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>Icon.png</PackageIcon>
		<PackageOutputPath>../</PackageOutputPath>
		<PackageTags>utility;extensions;crypto;logging;encoding;secp256k1;ecc;rsa;vieapps;vieapps.components</PackageTags>
		<PackageReleaseNotes>ConcurrentHashSet, CreateInstance, CastAs, Cryptors</PackageReleaseNotes>
		<PackageProjectUrl>https://vieapps.net</PackageProjectUrl>
		<RepositoryUrl>https://github.com/vieapps/Components.Utility</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<None Remove=".DS_Store" />
		<None Remove=".gitattributes" />
		<None Remove=".gitignore" />
		<None Visible="false" Include="README.md" Pack="true" PackagePath="\" />
		<None Visible="false" Include="LICENSE.md" Pack="true" PackagePath="\" />
		<None Visible="false" Include="Icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0' and '$(TargetFramework)' != 'net8.0'">
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="8.0.20" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.3.0" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
		<PackageReference Include="Konscious.Security.Cryptography.Blake2" Version="1.1.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="SharpCompress" Version="0.47.3" />
		<PackageReference Include="Snappier" Version="1.3.0" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0" />
		<PackageReference Include="ZstdSharp.Port" Version="0.8.7" />
	</ItemGroup>

</Project>
